### ISSUE TITLE
Match Schedule

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#45] opened 2018-10-03 22:50 UTC
I created a match schedule of 24 and then modified to a schedule of 29 but it didn't clear out the schedule of 24.  It doesn't appear that there is a way to clear a schedule if there is a conflict, to generate a new one.
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2444289/db.zip)

**Comment by adwiii** [comment] 2018-10-13 21:04
Duplicate of #75. I am closing this since #75 has a more descriptive title.

**Closed by adwiii** 2018-10-13 21:04 UTC
