### ISSUE TITLE
Schedule:  Default the date of new block to Event date, rather than current date.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#46] opened 2018-10-06 16:51 UTC
Since I have to set an event date range when creating an event, this seems like a great time to use this data...

**Comment by adwiii** [comment] 2018-10-08 22:04
This is a duplicate of #44. I am closing #44 since the title of this issue better captures the issue.

**Comment by emmell620** [comment] 2018-12-02 22:07
Would like to raise the priority of this up a notch. When doing qualifiers, the scoring system is generally set up a couple of days in advance of the actual tournament date.

**Comment by maths22** [comment] 2024-04-25 04:21
The scoring system now requires that matches be scheduled for event dates.  (If you need to schedule them for a date it isn't showing, you should update the event dates first, since you can't actually play matches on a date the event is not happening.)

**Closed by maths22** 2024-04-25 04:21 UTC
