### ISSUE TITLE
League Rankings "Back" Link is Incorrect

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#144] opened 2018-11-01 21:35 UTC
I am in the league rankings button under league info after importing a league.  When I click back to home button it gives this message this page appears to be lost in deep space... error 404

**Comment by rgutentag** [comment] 2018-11-01 21:37
Forgot to mention that once I click on the ftc logo and then the event everything looks ok until I do it again

**Comment by adwiii** [comment] 2018-11-01 21:38
Noted - the link will be updated in next release. The page itself is fine, the issue is that the "<< Back to Event Home" button has an incorrect link. The workaround until next release is to use the logo or browser back button to leave the page.

**Comment by adwiii** [comment] 2018-11-08 18:03
This has been resolved in 0.5.2

**Closed by adwiii** 2018-11-08 18:03 UTC
