### ISSUE TITLE
Non-show teams showing as played

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#163] opened 2018-11-05 13:59 UTC
We had 3 teams leave partway through our first league meet (it ran way over the planned time). We noted each team as not present for the start of each of their matches. At the end of the day, our records showed the teams that left as having completed the same 5 total matches as the other teams. We believe those teams should be showing as fewer matches played. This is not an urgent issue, as only the top matches are used for now, but it has created some confusion.

[roswellga-league-m1.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2548662/roswellga-league-m1.zip)

**Comment by adwiii** [comment] 2018-11-05 14:33
If a team is marked as a no show, then that match still counts; however, it does influence *how* that match counts for their rankings. For example, in Match Q14 of the event you uploaded above, Team 112 is marked as a no show for the Red Alliance. Thus, even though the Red Alliance won the match, Team 112 does not get the RP for the win. This is why Team 112 finished with 5 matches, but only 2 RP, coming from Q4 when they were on the Blue Alliance, present, and won. 

"Matches" in the header is misleading, because what it really means is "Matches that have been played in which this team was scheduled to play, whether or not the team was present". At the end of an event, all teams will have the same number of Qualification Matches, even if they do not show up to all of them.  

All that is to say that the behavior you observed is the expected behavior of the system.

If you have any followup questions about the influence of no shows on rankings, I would ask that you post them to the [Official Q&A forum](https://ftcforum.usfirst.org/forum/tech-challenge-rover-ruckus-presented-by-qualcomm) for the GDC (Section 5.8 of Game Manual Part 1 also contains more information). If you do, please post a link in this thread for consistency.

**Comment by vwestin** [comment] 2018-11-05 19:39
OK, that helps. As long as we can explain it, and they are not getting any ranking for those matches, that works. By the end of the season, all teams should have actively participated in at least 10 matches, so they will be 10 played (in the ranking summary). I believe it would be clearer if these were not counted in the ranking summary, but we can work with this. Thank you.

**Closed** 2018-12-09 02:09 UTC
