### ISSUE TITLE
Circuits not showing when created during final check on the tablets

### ISSUE THREAD

**Issue by Infinity8806** [FIRST-Tech-Challenge/scorekeeper#592] opened 2022-11-15 22:26 UTC
**Describe the bug**
I have noticed on a couple of occasions that if the Scoring referees create a circuit on the final check page, it does not show up in the UI.  The score is proper, but the board does not show the Circuit on the audience or field displays.  On each occasion, we checked it in the edit menu on the scorekeeper system, before committing the scores.

**To Reproduce**
1. Play a match
2. do the first submission of scores on the tablet
3. It then takes you to a final check page before you submit the scores.  Create a circuit for one of the alliances on that screen.

**Expected behavior**
The Line through the junctions and polls appears on the Audience and Field displays

**Device (please complete the following information):**
 - Scorekeeper Server OS: Fedora 36
 - Scorekeeper Browser Chrome
 - Tablet OS - IpadOS
 - Tablet Browser - Chrome

**Comment by KevinEmery** [comment] 2022-11-20 05:05
One of the developers can correct me, but I believe the audience display not updating to reflect changes made in Match Review is a feature not a bug (and that if anything, even if the scores, update then that should be fixed). At the very least that's the understanding we have in my region which is why at our events we ask referees to advance to the Match Review screen so that the score edits aren't shown in real time, allowing us to have close matches potentially be a surprise in the post-match score announcements.

**Closed** 2023-09-08 17:01 UTC
Labels: bug, Local
