### ISSUE TITLE
Printing reports with Mac gives weird texts on document

### ISSUE THREAD

**Issue by Rob4481** [FIRST-Tech-Challenge/scorekeeper#441] opened 2019-11-04 19:58 UTC
<img width="999" alt="Schermafbeelding 2019-11-04 om 20 46 28" src="https://user-images.githubusercontent.com/43778153/68152744-8e31d400-ff44-11e9-9665-a3b97d015389.png">
 In FIRST-Tech-Challenge-Live-1.1.2 I can't print any reports or match schedule. The scoring system creates a file with weird text as shown in the picture. 
I use a MacOS Catalina version 10.15 MacBook pro 2017 and Google chrome Version 78.0.3904.87

When we try to print reports on a windows pc it works fine.

**Comment by adwiii** [comment] 2019-11-04 20:08
Hm, this is quite the interesting find. A few questions to try to narrow things down:
1. Does the issue happen if you try to print to something other than a PDF.
2. Does this happen for browsers other than Chrome on the Mac?
3. Are the language settings for the Windows PC the same as the Mac?

**Comment by Rob4481** [comment] 2019-11-04 20:16
1. If I select a printer the file stays the same.
2. Just test it on Safari and there it works well, so it only happens on Google Chrome.
3. The language settings are the same on the Windows pc and Mac

**Comment by aj-foster** [comment] 2019-11-17 00:23
Can add +1 the above comments; we got around the issue by using Safari for printing during our last League Meet.

**Comment by adwiii** [comment] 2019-11-18 15:11
@aj-foster same system and browser as OP?

**Comment by aj-foster** [comment] 2019-11-18 18:07
Exact same versions. 👍

**Comment by hardcopi** [comment] 2020-01-16 13:25
Just tested it with the newest version, with the newest Chrome on a fresh Catalina install. Problem does exist. It is a Chromium issue they are working on. No clue on a time frame for the fix, it was reported at least 2 weeks ago.

The issue is saving to PDF a document that uses the browser's own built in fonts AND there being italics text anywhere on the page. At the bottom of this page the _FIRST_ name is in italics.

Here is a suggested solution that  worked for me:
Change:
`<i>FIRST</i>`
To:
`<i style="font-family: arial">FIRST</i>`

Gives you the same look and feel, but by specifying Arial then you end up forcing it to render properly in the PDF. You can test this working by using "Inspect Element" and changing the sections and reprinting.

**Comment by adwiii** [comment] 2020-01-17 03:02
This has been addressed in `v1.3.1` by removing the Apple fonts for italics. This may cause *FIRST* to appear slightly differently as it will now be in a similar but different font. Please re-open this issue if you continue to have difficulty. This is a [known issue in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1018581) and we can continue to monitor that and revert back to original fonts at a later time.

**Closed by adwiii** 2020-01-17 03:02 UTC
Labels: In Development
