### ISSUE TITLE
Can not edit score after commit for 1.1.0-1

### ISSUE THREAD

**Issue by firstrgv** [FIRST-Tech-Challenge/scorekeeper#430] opened 2019-10-19 23:55 UTC
Had a league meet today using 1.1.0, tablet scoring.  We had an error in one match and went back to edit and as soon as we clicked edit it zeroed out the match but would let us edit it.  We canceled the edit and just advised the team we would solve the issue before the next match.  We did not have this problem in 1.0.0.   

We have another league meet this coming weekend and need a workaround or fix please.  

No other bugs noted.   Thanks

**Comment by adwiii** [comment] 2019-10-20 01:23
Can you post the logs here and the downloaded archive db for the event? Were you able to make the edit later on?

**Comment by firstrgv** [comment] 2019-10-20 20:51
Our scoring laptops are at the storage unit but will go get them on Monday to pull the logs. We were never able to edit the score.. even after the event was over.

We had to add a yellow card to a different match as it approached.

All times we tried to edit a previous match, it zeroed out the score. As we were using tablets.. we had no reference to regenerate the score so we did not save the edit and canceled out of it.

The event is archived with HQ using their new secure upload process. Our region is Tx-South.

Thanks for looking into it.

-----

Jason Arms, President
FIRST RGV, INC.

956.320.9311. Office
956.257.9777  Direct

720.820.1656  Conference / Training Bridge

https://firstrgv.org

Local Program Delivery Partner of FIRST for South Texas
The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by jvens** [comment] 2019-10-20 21:18
I had a report of the exact same issue from one of the scorekeepers at a league meet in Iowa this weekend.  They attempted to edit a match score after it had been committed and when they clicked edit he said all of the scores were cleared out.  The score change wasn't going to effect the outcome of the match, so they just decided it wasn't worth fighting to change it.  I have asked the scorekeeper to send me the logs and as soon as he does I will post them here.

**Comment by adwiii** [comment] 2019-10-20 21:40
@jvens do you know which meet it was?

**Comment by jvens** [comment] 2019-10-20 21:42
It was Mandalore Meet 1 (mandalore_2019_10_19_meet1)

**Comment by jvens** [comment] 2019-10-21 13:50
Attached are the log files.  The one from 10/16 is from when I imported the event that had been created on v1.1.0 into a server running v1.1.1.  The log from 10/19 is the actual event day.  They were running the TOA DataSync which is why there are all the extra API calls in the log.

[2019_10_16_12_47_29_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3751133/2019_10_16_12_47_29_PM_err.log)
[2019_10_19_08_33_46_AM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3751134/2019_10_19_08_33_46_AM_err.log)

Let me know if there is anything else I can provide that would be helpful.

**Comment by adwiii** [comment] 2019-10-21 19:00
@jvens I know you are reporting this second hand, but do you know for sure which match it is? (my guess is match 4). Also, do you know if this issue persists if the system is restarted? I have not been able to duplicate the issue locally - all of the matches allow me to edit them with proper scores, and I have not been able to duplicate it locally. I will keep trying, but any additional details you have would be helpful. 

I am also curious if the electronic score sheets in the Match Result report was incorrect, though I realize that was not checked in the moment. From the event home page, the Match Results link provides a page where you can select to view the score sheets for every match. For match 4 for example it would be `http://localhost/event/mandalore_2019_10_19_meet1/match/q4/` which shows the Red and Blue score sheets rendered side by side. These show correctly for me locally. If you encounter this again it would be useful to know.

@firstrgv and @jvens in any case, we want to make the scores are right since it will affect rankings (TBP and highest score possibly) moving forward since league meet matches carry over. If you cannot make the edits locally, do you know what changes need to be made and I can make them for you and send you the proper db?

**Comment by firstrgv** [comment] 2019-10-21 20:05
Ours were minor changes except for the yellow card.  We added the yellow card the next time the team competed.

For us we got no errors and everything else worked fine.

For clarifications, we did not restart the software since we were scared our linked displays would time out and have to be logged back in.

We did not see any errors and the issue about editing matches was consistent all day.   We could go in and edit before the match was committed.  Once we did that. Returning to the match to make an edit caused both alliances to show zero points.  We canceled out of the edit and went back to the active matches.  We are running Windows 10 and using Chrome.  Single browser open on the computer. Logged in as local.

If you can’t replicate it then we will do the best we can this coming Saturday as we will have to figure out a workaround

Jason Arms, President
FIRST RGV, INC.

956.320.9311 Office
956.257.9777 Direct

https://firstrgv.org

Together, We Are FIRST
________________________________

**Comment by jvens** [comment] 2019-10-22 02:53
@adwiii, I asked for more details and the scorekeeper screen captured the exact steps that he did on Saturday.  He was unable to replicate the issue even using the same score system, but shows exactly what steps he took to do it.  Also, you are correct that it was match 4 that the issue occurred.

Here is the screen capture he sent me: https://youtu.be/tseILme3Vp8

I will be able to fix the match score in the database before I import it into the next league meet.

**Comment by ftctechnh** [comment] 2019-10-22 17:30
@firstrgv 
Jason - when is your next league meet scheduled?  Is it this Saturday (10/26)?

**Comment by firstrgv** [comment] 2019-10-22 18:48
Yes.  It is this Saturday the 26th.  We have an AM and PM session.  Two separate leagues with approximately 60 teams for the day.

We run two fields and do live scoring.

Jason Arms, President
FIRST RGV, INC.

956.320.9311 Office
956.257.9777 Direct

https://firstrgv.org

Together, We Are FIRST
________________________________

**Comment by ftctechnh** [comment] 2019-10-22 19:52
@firstrgv @jvens 
Thanks folks for reporting this issue.  I am able to reproduce the issue and have provided some info to the developers that hopefully will help them identify and resolve the issue.

Until a fix is released for bug, if you need to edit the score for a match that has been already committed, then you will need to follow the workaround as described in the following YouTube video to edit, save and commit the updated score:

https://youtu.be/s6eNSTtcsYg

We'll post updates on this issue thread as they become available.  Thanks again for your help in identifying this problem.

**Comment by adwiii** [comment] 2019-10-30 02:50
This has been fixed in v1.1.2

**Closed by adwiii** 2019-10-30 02:50 UTC
