### ISSUE TITLE
Dual Division - Division finalist/winners not reflected when presenting final awards

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#499] opened 2020-02-25 22:02 UTC
It would be great if the division finalists/winners could be reflected when presenting the awards at the conclusion of the dual division championship.  We typically present all awards at the end of the event and not at the conclusion of each division.  We wait until the finals are completed, not sure how others present.  During the event with two divisions going on, the system would not let me access the division awards since I had entered/completed the dual division championship awards, I was logged in as the main server for our event.  I can now go back in and see that each division has the details (finalist/winners) of each division.

**Comment by maths22** [comment] 2020-02-26 00:39
Dupe of #355

**Comment by maths22** [comment] 2022-05-05 20:35
Closing as dupe of #355

**Closed by maths22** 2022-05-05 20:35 UTC
