### ISSUE TITLE
Rankings on Match Preview not using combined rankings at league meet V1.2.0

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#457] opened 2019-11-23 16:16 UTC
![rankings](https://user-images.githubusercontent.com/32021115/69481805-14219c00-0dda-11ea-95fb-8742b5b07d39.jpg)
![Rankings Report - TEST Fox Valley South Meet 2 Combined-1](https://user-images.githubusercontent.com/32021115/69481995-a9716000-0ddb-11ea-862c-c63ec9b5f298.jpg)
![Rankings Report - TEST Fox Valley South Meet 2 Combined-2](https://user-images.githubusercontent.com/32021115/69481998-ad9d7d80-0ddb-11ea-809a-81f46a939ef0.jpg)

**Comment by jvens** [comment] 2019-11-25 21:00
This is a duplicate of #442 with a nearly identical title.  @GamingWithaAlexYouTube, please check to see if an issue has already been posted before creating a new issue.  If you have more details to add, please add them to the already existing discussion thread instead of creating a new one.

**Comment by adwiii** [comment] 2020-11-04 03:37
Closing in favor of #442

**Closed by adwiii** 2020-11-04 03:37 UTC
