### ISSUE TITLE
View Audience Display without Login

### ISSUE THREAD

**Issue by bkeeneykid** [FIRST-Tech-Challenge/scorekeeper#368] opened 2019-07-31 01:40 UTC
I'm attempting to use [obs-linuxbrowser](https://github.com/bazukas/obs-linuxbrowser) to show the audience display inside of OBS without having to run a chrome window in the background. However, this package doesn't have any support for interacting with the window that's being rendered inside of OBS, so it makes it impossible to log in to the scoring system, even as local. For our specific need, OBS is running on the same computer as the scoring system, so I would love any of the possible enhancements:

- A custom URL that's slightly modified from the standard audience display URL that allows viewing without logging in, if it's being viewed from `localhost`
- Not redirecting for the audience display at all if being displayed from `localhost`.
- Some sort of URL-based authentication system

**Comment by jvens** [comment] 2019-07-31 19:36
This is a duplicate of #149.

I agree with @bkeeneykid in a desire for a method to login to the display page using a URL based authentication scheme as it would be much easier to do exactly what is asked for here of using the browser built into OBS.  Personally I do not like the first two suggested fixes for this problem because they only resolve for the case that the obs streaming computer is running on the same machine as the score server which will not always be the case, and in most cases should not be the case.  Assuming you are using OBS for live streaming the event you would need the OBS computer to have internet access, but the score system computer really should not have access to the internet as this could cause security concerns.

All that said, there actually is a way to login to the display using the OBS browser, and it is how I did set up the live stream at all of my events last season.  After adding the browser source in OBS studio you can right click on the source in the sources list and select `interact`.  This will open a separate browser window that will allow you to interact with the web page including logging in and navigating to the display page.  One warning about this is if you have that source visible your interactions will show up on the stream, so please take that into account when logging into the server.  If you have any questions about how to set this up please feel free to ask and I am happy to help.

**Comment by bkeeneykid** [comment] 2019-07-31 19:43
Ah, I missed both the duplicate issue and the interaction for the OBS browser. I can't test it right now, but I'll double check that it works properly tonight. While my specific use case for this right now isn't necessary anymore, I still think having some kind of method to display this page without interaction would be quite handy, so I don't think I'll be closing this ticket (unless marked as a duplicate)

**Comment by adwiii** [comment] 2019-09-11 14:42
See #149

**Closed by adwiii** 2019-09-11 14:42 UTC
Labels: In Development
