### ISSUE TITLE
Incorrect "Already Advancing" Calculations

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#247] opened 2018-12-10 19:26 UTC
Both last week and this week, we've had team that previously advanced that were not marked as such in the advancement report.  After we archive and shut down the system, the next time it come up, it is correct.
Here an example from this weekend:
Team 5962 is marked as advancing in team list

AdvanceReportA (picture of piece of paper) is what is generated at the qualifier. I went back and forth the re-display this many times, each time it came up with 5962 not being marked as advancing as Inspire winner. 
AdvanceReportB is what is generated after I archive, shut down and restart. So I'm unable to re-create the problem.  Last week there were more issues, with a very confusing set of "Already Advancing" and Advancing above" and one team that didn't even show up on the advancing report at all.

I can pull all that out too, but it appears something is not being properly saved until shut down.

![advancereportb](https://user-images.githubusercontent.com/44174505/49756209-60360800-fc7f-11e8-96d0-4ab5650e16a7.jpg)
![teamlist](https://user-images.githubusercontent.com/44174505/49756210-60360800-fc7f-11e8-94f0-c7ef75a24afb.jpg)
![advancereporta](https://user-images.githubusercontent.com/44174505/49756211-60ce9e80-fc7f-11e8-9e7c-f0a5f4dca8bf.JPG)

**Comment by adwiii** [comment] 2018-12-10 20:16
I have been able to reproduce the issue involving rebooting the server. I will continue to investigate.

Can you explain further what happened with the team that did not show up being present in the advancement report? Where they part of the rankings advancement or an award? Were they still listed in the team list for the event?

**Comment by hightechkids** [comment] 2018-12-10 20:51
Here's what happened last week (along with the "already advancing" problem.)

We had a team that had already advanced. That did not win any awards and
was not the winner/finalist alliance this week. They did not show up in the
Advancement report at all. Nowhere.

I just pulled it up again and the problem still exists, I can send you the
archive if you'd like.
The picture is the team list - 10364 - Time Pilots is in the tournament,
competed and is marked as already advancing.
They were ranked 4th in qualifying matches, but their alliance lost in the
semis. I think they should have shown up in the advancement report as 16 -
highest ranked team not previously advanced.
But the PDF of the advancement report does not have10364 listed anywhere.

Norm Tiedemann
norm@hightechkids.org

**Comment by adwiii** [comment] 2018-12-10 20:57
If they had previously advanced at another tournament as you indicated, then they do not show up in "highest ranked team not previously advanced" because even though they did not advance at this tournament they still are an advancing team. Since they advanced at a previous tournament, 10364 would only appear in the list if they won an award or were on the winning or finalist alliance.

**Comment by hightechkids** [comment] 2018-12-10 21:23
Interesting. OK - Thanks. I don't remember seeing it this way in past
years, but can't say I ever really checked.

I just assumed that all teams in the tournament would be listed. They would
be shown in proper order and it would indicate "Already Advancing". I
thought the "not already advancing" statement only applied to this
tournament, but I see your point.

Thanks for explaining it. Good luck with the other problem.
Norm T.

**Comment by adwiii** [comment] 2018-12-13 16:32
The issue of "Already Advancing" not taking effect until the server has been rebooted has been fixed in v0.6.1

**Closed by adwiii** 2018-12-13 16:32 UTC
