### ISSUE TITLE
All Matches Played on Same Field After Import

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#388] opened 2019-09-19 03:04 UTC
The match schedule generates all matches to be played on the same field, regardless of how many fields are present at the event.

**Comment by adwiii** [comment] 2019-09-19 03:53
Can you post the db file of the event you were testing with? I cannot duplicate this locally.

**Comment by bsimmons99** [comment] 2019-09-19 05:17
It looks like this is not a problem with the match generation, rather when the db is imported into another server, the field data is lost. Updated issue accordingly.
[test0.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3629510/test0.zip)

**Comment by adwiii** [comment] 2019-09-19 14:26
Ah, I found the issue. The field is incorrect only immediately after import - if you reboot the server it fixes it. Can you confirm that is true for you? I have a fix for that, but I want to make sure the problem isn't bigger than that.

**Comment by adwiii** [comment] 2019-09-19 14:31
To clarify - you mean when you import an event that already has a schedule generated and then look at the match schedule all of the fields are wrong (I believe they all show field 0). There are 3 scenarios I have tested:
1. Import a multi-field event that has not had a schedule generated yet. Generate Schedule. The Schedule generates correctly.
2. Import a multi-field event that has a schedule. All matches show as field 0. This is incorrect behavior, but rebooting the server corrects this. (and I will fix this for next release)
3. Import a multi-field event that has a schedule. All matches show as field 0. Re-generate the match schedule. The fields show correctly.

Your issue is exactly the second one, yes?

**Comment by bsimmons99** [comment] 2019-09-20 03:28
Yes this is correct, my issue was the second one, and rebooting the server did correct the issue.
I tried it with a single field event and found the same results (field shows as 0 after import, reboot fixes).

**Comment by adwiii** [comment] 2019-10-10 19:56
This has been fixed in v1.1.0

**Closed by adwiii** 2019-10-10 19:56 UTC
Labels: In Development, bug
