### ISSUE TITLE
Impossible Latch + Park Allowed

### ISSUE THREAD

**Issue by cheer4ftc** [FIRST-Tech-Challenge/scorekeeper#200] opened 2018-11-18 11:03 UTC
The scorekeeper software allows scoring refs to score an End Game Latch and a Park (which should not be possible according to the rules), leading to incorrect scoring (e.g., VA-Orange Match F3 scored End Game 115 points for Blue). Please fix to auto-unpark if Latch is selected or auto-unlatch if a Park option is selected.

**Comment by mglennon** [comment] 2018-11-18 13:55
I suggest the two situations @cheer4ftc posted are handled by turning the background of the offending switches orange in real-time. Also, since they are different point values and the manual states that the higher value will be scored, perhaps the scoring software can do this logic automatically.

**Comment by beads27** [comment] 2018-11-18 17:43
I agree with Cheer4FTC: it would be very simple in the code to prevent a scoring of an impossible situation, like a robot latched and parked simultaneously.   It would make sense to me to have the "impossible" option grey out (or turn orange) to notify that the scorer that the parking option is not available due to a previous latching selection.

**Comment by adwiii** [comment] 2018-11-18 18:04
This is a duplicate of #156 (really a sub-issue), and related to #71 and #20. This is not a bug so much as a feature that has not been implemented and we are aware of the community's desire to see it implemented. However, it is not a high priority because the scoring referees must pass the training for their position and should know not to score both states.


Note, this is in reference to [this forum post](https://ftcforum.usfirst.org/forum/tech-challenge-rover-ruckus-presented-by-qualcomm/game-rules-ab/explore-the-game-manual-for-the-answer-aa/66510-robot-both-latched-and-parked-in-the-end-game) relating to &lt;G24&gt;

**Comment by beads27** [comment] 2018-11-20 21:55
I was the offending ref in a finals match that completely inadvertently touched the scoring bar for a parked robot when both blue team bot had already successfully latched; and feel really crappy about it.  I absolutely did not intentionally select both park and latched for the same bot, but the fact of the matter is code could prevent it- or at least create flag like "there's and inconsistency- are you sure" before allowing final submit.  We were the first test of the software in Virginia- overall it went pretty well, but there are definitely things that could be improved, including this issue.  My bet is that the developers didn't test the chance of a miss-score or inadvertent actuation in a real world situation: with music blasting, crowd cheering, and the scoring refs getting bumped by excited teams on either side (a result of new ref positioning this year).  Haptic feedback after each selection may also mitigate; but the first answer should be the code shouldn't allow impossible scoring.

**Comment by marcsol** [comment] 2018-11-24 17:43
Maybe I am confused, but while latched and completely in the crater is mutually exclusive and should not be allowed by the system, couldn't a robot be latched and partially in the crater? 'In' is defined as breaking the plane extending up from the edge of the area (the crater wall in this case). Is it not possible for a robot to be latched on the lander and extend an arm over the crater wall? As long as the arm does not touch the ground, the robot would be both latched and partially in the crater, no? 
If that is the case then we need to allow for both items (latched and partially in) to be scored. This would mean there are 5 options: neither latched nor in the crater, latched but not in the crater, latched and partially in the crater, not latched but partially in the crater, not latched but fully in the crater. This means the only option currently allowed that shouldn't be is latched and fully in the crater. 
I assume the easiest fix would be to grey out fully parked when latched is selected and grey out latched when fully parked is selected. Another fix would be to list the 5 options but whether it was implemented as a drop-down or a set of radio buttons, I think it would make the referees' job more difficult as compared to the current layout.

**Comment by cheer4ftc** [comment] 2018-11-24 18:56
A robot cannot receive endgame points for both latching and parking: only the highest scoring achievement is scored. So from the scorekeeper software perspective, simultaneous end-latching and end-parking scores should never be allowed for the same robot even if a robot is in both states and/or even if a ref scores a robot as being in both states.

**Comment by jvens** [comment] 2018-11-24 19:08
I don't see anything in the game manual about only being able to score one end game achievement.  In fact 1.5.4 seems to imply the opposite.  Assuming this is the correct interpretation I agree with @marcsol on the solution.

**Comment by emmell620** [comment] 2018-11-24 19:19
<G24> Robot or Scoring Elements In Two or More Scoring Areas – Robots or Scoring Elements that are In two or more Scoring Areas earn points only for the highest value achievement. If the achievement values are equal, only one achievement counts as Scored. Exceptions to this general rule may be specified in the Game Play section (1.5) or in the game-specific rules.

While 1.5.4 doesn't specifically state that you can score in more than one, then this rule <G24> applies.

**Comment by marcsol** [comment] 2018-11-24 20:19
Well, that still leaves us with 4 distinct end game conditions: neither latched nor parked, latched, partially parked, completely parked. The system should at the minimum lockout both parked conditions if latched is selected and lockout latched if either park condition is selected. A better solution would be to give the referee just four radio buttons one for each of the four options listed above.

**Comment by adwiii** [comment] 2018-11-27 05:13
As an interim fix, I think the simplest idea is something like what @mglennon proposed of having the UI indicate that something is wrong by highlighting the related inputs. Below is a screenshot of what this would look like. 
Long-term I will look into ways to make it so the user cannot enter such a state, but what is described here will be in this week's release.

![image](https://user-images.githubusercontent.com/9453262/49059686-0aba1f80-f1d8-11e8-8854-b3c31a880387.png)

**Comment by beads27** [comment] 2018-11-29 03:09
The highlighting is definitely an improvement over no indication- but it isn't that much of a flag.  As a US Navy test pilot with experience in OMI (Operator Machine Interface), I can say this wouldn't "fly" in that world.  Rather than a light red halo, could both the entire bars switch to red, as the lathed one is below (but make both blaring red)?  Since the forums and the comments above have verified that a robot cannot score in the crater and also be latched, it seems like the code could be written where only one option can be submitted.  Based on the way this appears- a fat-fingered ref like me could still submit a score that is impossible.

![latched](https://user-images.githubusercontent.com/43122556/49196726-fdc53980-f359-11e8-93dc-ae21b1bd1e40.png)

**Comment by gearsincorg** [comment] 2018-12-03 13:33
Seems like we have two different scenarios to resolve here..

As previously stated, In the case of "partially in", it is absolutely possible to be both "latched" and "partially in" the crater.  So it does not seem unreasonable that the display can show these two conditions simultaneously.   However, the code should correctly implement the rule of only assigning points for the highest achievement in this instance. So, no UI change required... just fix the math.

In the case of mutually exclusive goals (latched and completely-in) then the display should either prevent or at the least highlight the discrepancy to enable a human review to determine the actual state.

**Comment by jkelbick** [comment] 2018-12-10 13:49
We need the software to insure quality inputs. When there is a logical inconsistency, the software should **not** make the scoring decision until the issue has been flagged for referee. If the referee doesn't correct it, then the software should follow the pre-established scoring criteria from <G24>. All attempts should be made to ensure accurate data entry and minimize typos. Most of these situations will come from typos.

**Comment by jkelbick** [comment] 2019-01-31 20:25
Can we get the scoring software to stop allowing illegal scores? Highlighting the error in red is a good start, but the scoring software is still giving the alliance points for parking and hanging. As has already been discussed, teams cannot earn points for both. Even if the referee incorrectly enters both, the scoring software should cap end game points at 50 to minimize the impact of data entry errors.

**Comment by adwiii** [comment] 2019-09-11 15:28
For the SKYSTONE season we have added several safeguards for illegal scoring states. The system actively checks that the tallest Skyscraper is at least as tall as the highest Capstone level, and we have designed the inputs to prevent access to inputs that would not make sense. There are a few known "illegal" states that we do not intend to prevent at the moment. For example, the system does not count the total number of Stones in play. The system also allows for all 6 of the Autonomous stones to be marked as Skystones - although this is obviously not possible, the system still calculates points correctly as if the extra Skystones were Stones. We hope we have achieved a good balance of making the user interface simple while also preventing the obvious mistakes. Please open a new issue if you wish to discuss an equivalent scenario for SKYSTONE.

**Closed by adwiii** 2019-09-11 15:28 UTC
Labels: Rover Ruckus
