### ISSUE TITLE
Video Switch option - Rankings

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#280] opened 2019-01-02 20:34 UTC
It would be nice if there was an option to switch video to rankings from the scorekeeper position when on a break (lunch).  We can switch to sponsors for ours but having an option for rankings on our screen connections would be nice.  We typically have them posted in the pits on a different set up but we don't have them at the scoring table/screen.

**Comment by adwiii** [comment] 2019-01-03 20:18
Closing this issue as a duplicate of #134

**Closed by adwiii** 2019-01-03 20:18 UTC
