### ISSUE TITLE
Field Display shows blank screens when user on Match Control screen clicks either "Show Preview" or "Video Switch->Show Sponsors"

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#101] opened 2018-10-22 02:13 UTC
As you've probably figured out from the title, the Field Display shows blank screens when user on Match Control screen clicks either "Show Preview" or "Video Switch->Show Sponsors". This directly affects the setup we have for a scrimmage that we are running in December, and from what I've seen maybe it is supposed to be a blank screen but the way that the blank screen was laid out looked unfinished. Attached is a video recording of the exact issue that I'm seeing as well as the db folder of the match control computer.
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2499971/db.zip)

**Comment by adwiii** [comment] 2018-10-22 14:57
Closing as duplicate of #102

**Closed by adwiii** 2018-10-22 14:57 UTC
