### ISSUE TITLE
Live Scoring does not allow marking for "landing"

### ISSUE THREAD

**Issue by nebomusic** [FIRST-Tech-Challenge/scorekeeper#147] opened 2018-11-02 20:12 UTC
The Live Scoring allows selecting for "Latched" but does not allow scorer to mark as landed during Autonomous.  Tested in 5.1

**Comment by adwiii** [comment] 2018-11-02 20:47
Can you please post a screenshot and steps to reproduce? I just tested this and cannot reproduce the issue. A team must be marked as "Latched" during initialization in order to be able to mark them as "Landed" in Autonomous. Otherwise, the "Landed" option is disabled.

**Comment by adwiii** [comment] 2018-11-02 20:53
Also, what browser/device are you using for the scoring input?

**Comment by nebomusic** [comment] 2018-11-02 21:17
Greetings

iPad Safari. I marked teams as latched and ran test match. Options grayed out in auto.

Mr. Michaud
Computational Media and Robotics
Marist School

On Nov 2, 2018, at 5:06 PM, Trey Woodlief <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, what browser/device are you using for the scoring input?

**Comment by adwiii** [comment] 2018-11-02 22:15
Can you try it in Chrome on the same iPad? I will see about reproducing this issue but right now it appears to be working in Chrome for me.

**Comment by nebomusic** [comment] 2018-11-02 23:39
Thanks for the help.  I will try with Chrome on iPad.  Thanks.

**Comment by nebomusic** [comment] 2018-11-03 00:00
Still getting greyed out selections for landing.  Running on Mac OSX 10.13.4 and using Chrome.

![sample latched](https://user-images.githubusercontent.com/7443882/47945685-fc7b2b00-ded9-11e8-8135-552667d8e769.png)

![sample greyed out](https://user-images.githubusercontent.com/7443882/47945689-000eb200-deda-11e8-8379-0678bd979bd5.png)

**Comment by cmacfarl** [comment] 2018-11-03 00:10
What happens if you don't use negative numbers for teams?

**Comment by adwiii** [comment] 2018-11-03 00:15
Yes, it appears that might be the issue - I was able to reproduce it locally but only using negative team numbers in a test match. If you run a non-test match or a test match with actual teams this does not happen. Thank you for bringing this to our attention. 

To be clear, this does not affect running regular matches - please verify this in your case as well.

**Comment by nebomusic** [comment] 2018-11-03 00:17
Yes - that is the issue.  If I run a test match with actual team numbers the latching and then landing works in the scoring.  

Also - a robot that is "not latched" can still be marked as climbing in driver control.  Thanks for the help.

**Closed** 2018-12-09 02:13 UTC
