### ISSUE TITLE
scoring referee input device

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#49] opened 2018-10-08 22:05 UTC
We were running some practice matches.  We found that we could input end game events before end game period start.  If would be nice if this didn't happen.  It would also help if the area that is the end game events on the screen could be highlighted with something like a box around this area.  What would be very helpful if a label could be red during the time before end game starts and then turn green during end game.

**Comment by cmacfarl** [comment] 2018-10-08 22:13
I think this merits some discussion.  I've noticed this also, but if a team finishes early it might useful to a scoretracker to be able to enter the state that team is in early.  I think this one could go either way.

I do agree that it might be useful to make it more clear what elements are end game points, but then again, the person doing the scoring is supposed to be ref-certified, so... :-)

**Comment by adwiii** [comment] 2018-10-08 22:14
This is a duplicate of #5 functionality-wise. 

However, I believe it is not in the spirit of live scoring to limit this scoring to end game only, as live scoring attempts to provide a best effort "what is the score if the match where to end right now". As such, if a robot moves into the crater and gets stuck there, then it would be sensible that the referee could mark them as scoring the end game points for parking so that the score would reflect their current state.

I can understand the argument that attempting to latch early is against &lt;GS7&gt;, and thus latching should not be allowed to be scored, but that is not all of the end game achievements, and as @cmacfarl says, the referee should be trained to know this.

**Comment by adwiii** [comment] 2018-12-09 02:20
Closing as there has been no new discussion. Please revive this issue or create a new one if this needs to be discussed further.

**Closed by adwiii** 2018-12-09 02:20 UTC
