### ISSUE TITLE
Cannot logout on Silk

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#693] opened 2024-01-16 01:20 UTC
**Describe the bug**
Was at an event with Kindle Fire tablets using the Silk browser. Inspectors had logged in and successfully used the tablets. When we tried to logout, the tablet would return to the home page still logged into the inspector account. (cookie not being reset?)

Workarounds that were identified included navigating manually to `/login/default` to pick a new user to login as, or clearing browser cookies.

**To Reproduce**
1. Login as one user
2. Click on the username in the top right, and click the red "logout" button.
3. Observe that, in the top right, the user is still logged in

**Expected behavior**
The user is logged out

**Screenshots**
video: https://i.imgur.com/vYGrCjm.mp4

**Device (please complete the following information):**
 - OS: [e.g. iOS] Fire OS 7.3.2.9
 - Browser [e.g. chrome, safari] Amazon Silk 118.1.77.5993.111.10
 - Fire HD 10 (9th generation)

**Additional context**
I heard of another event experienced a similar issue, which ~~I believe was using non-Amazon tablets (Samsung? i.e. using Chrome)~~ [edit: the FTA for this other event reports they actually *were* Fire tablets, but using Chrome]. Personally, I have only been able to reproduce this on my personal Kindle Fire tablets with Silk. As a test, I installed Chrome onto my same tablet and was not able to reproduce the issue.

**Comment by maths22** [comment] 2024-01-16 14:29
Can you upload server logs where this is happening?  Logs can be found in `~/Library/Logs/org.firstinspires.ftclive-2024-default`

**Comment by tweirtx** [comment] 2024-01-20 05:02
I just tested this locally and cannot reproduce...strange

**Comment by maths22** [comment] 2024-05-05 03:48
This appeared to actually be an issue with logging out after logging in with a QR code.  It has been fixed in v5.4.0.

**Closed by maths22** 2024-05-05 03:48 UTC
Labels: bug, Local
