### ISSUE TITLE
When using the overlay audience display, Audience Key display background does not use selected overlay color.

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#410] opened 2019-10-10 22:24 UTC
I'll try and explain this the best I can. When starting the audience display, the display options have an option to select which overlay color you want. The two default colors are green and magenta. If I select magenta and I set the display to use the "Audience Key", the background is still the green color even though I selected magenta.

![ghi1](https://user-images.githubusercontent.com/33290191/66610957-18c42500-eb8b-11e9-9989-2f8ba5f3e756.PNG)
![ghi2](https://user-images.githubusercontent.com/33290191/66610958-18c42500-eb8b-11e9-8f2e-1f5ed69efa29.PNG)
![ghi3](https://user-images.githubusercontent.com/33290191/66610959-18c42500-eb8b-11e9-8a95-76eb61d98bd7.PNG)

**Comment by bsimmons99** [comment] 2019-10-11 05:54
This is because the audience key images are literal images, with a "hardcoded" overlay color (washed out).
In the meantime you can work around this by modifying the overlay_*_key*.png images (there are 4, [auto | driver ctrl] & [top | bottom]) in the lib/public/img/bg/ directory to use your overlay color of choice (See my comment in #411).

(Dev: Potentially could fix by setting this region of the images to be transparent and then place the image over the top of the chosen overlay color.)

**Comment by adwiii** [comment] 2019-10-11 15:44
@Tomrish if we do what is suggested above and and sub in the correct chroma color, will the gray over the chroma color mess it up? For example, here is the above image but with magenta subbed out, but the magenta is still grayed over:
![image](https://user-images.githubusercontent.com/9453262/66665380-6b015680-ec1c-11e9-8d1c-6ac83d30b1e3.png)

**Comment by jvens** [comment] 2019-10-11 15:58
@adwiii, I am not sure I understand your question exactly.  What I believe @bsimmons99 is suggested is to add a transparent alpha to the .png file instead of any color and then handle the chroma color in HTML.  This way you would see the correct chroma keyed out video around the grey info box.  The file would look something like this:

![overlay_dc_key](https://user-images.githubusercontent.com/7074504/66666269-e3184e00-ec15-11e9-994e-83e4c80834ef.png)

_note: GitHub is making the transparent part white, but it is really transparent_

**Comment by adwiii** [comment] 2019-10-11 16:03
My question is if we can keep the gray over top of the chroma color instead of just going transparent. I have made the adjustments to the file so that it is not always green and instead it is a transparent gray. I then ran that through the scoring system and took a screenshot of what it would look like with a magenta background. My question is if using the transparent gray over the magenta  (or green or any other color) will render well enough, or if we need to not gray out the chroma at all.
For reference, this is the file with the transparent gray:
![image](https://user-images.githubusercontent.com/9453262/66666630-127f8880-ec1f-11e9-90ed-d2cff81004dc.png)

**Comment by Tomrish** [comment] 2019-10-11 16:08
@adwiii I think I understand what you're trying to say. From what I've tested as long as I'm using a _chroma_ key and not a _color_ key the grey over the overlay color will not make a difference, as the chroma key is very good at recognizing the entire range of the color. Basically, as long as the software makes the color in the background correspond to what is selected in the display options, it'll work just fine and render properly.

**Comment by jvens** [comment] 2019-10-11 16:12
@adwiii, I understand now.  I like what you are trying to achieve where the video content would appear greyed out and darker.  The problem is depending on what the similarity settings are on the chroma key it might make the magenta or green two different from the set value and it wouldn't get keyed out fully or at all.  I can test with both OBS Studio and an ATEM video switcher this evening and see how well it works.

Another possibility is to not try and have the chroma key on the edges at all on this page and just make it grey like the picture above.

**Comment by Tomrish** [comment] 2019-10-11 16:14
@jvens I probably should've mentioned that I'm using OBS studio to perform my chroma keys and it isn't having any issues recognizing the color range; the audience key is still keying out just fine. I also wouldn't be opposed to having a solid grey background, it's just that having it fluorescent green looks bad.

**Comment by Tomrish** [comment] 2019-10-16 22:51
@adwiii Just tested with the new release in OBS and when using a green overlay color the audience key background keys out just fine, however when using a magenta overlay color the background does not key out and changing color similarity and other settings even slightly begins keying out the reds on the live scoring bar. I didn't see this in testing as I was only using green at the time and green did not reproduce this issue. 

I would still prefer to use magenta for my overlay color as using green with a chroma key in OBS keys out some unintended objects (ex. PTC Logo) per other documented issues. I don't know if there is anything that can be done about this on your end, and I'm not experienced with professional-grade video switchers so I don't know if they would have the same issue. I'll let @jvens test that as he said he has an ATEM video switcher.

I wouldn't mind if you took out the gray tint and left the overlay color in the image at 100% opacity, however I can see aesthetically why you'd want it to have that tint, so what I might end up doing is just modifying the image in Photoshop and taking out the tint for my use case if you aren't able to tweak this any further.

**Comment by jvens** [comment] 2019-10-17 00:42
@Tomrish, I tested with the ATEM and it looks pretty good.  I was having issues with green, but to be honest I didn't try to tune it in very well because I only plan to use magenta.

With magenta overlay everything else works great but all I see on the overlay page is just grey around the edge.  A very faint amount of background comes through that I can kinda tell if I am moving my hand in front of the camera, but most of it is getting blocked.  Here is a screenshot of what it looks like overlayed over the camera shot of my bookshelf with lots of stuff on it.

![Capture](https://user-images.githubusercontent.com/7074504/66968793-68ec2d00-f04c-11e9-8429-21271e9068b1.PNG)

Also, I noticed there is a weird rectangle at the very top of the page (I think it shows in the screen shot above).  This is not an artifact of the chroma key; I can see this rectangle in the browser window providing the overlay to the video switcher.  That page is running in Chromium on a raspberry pi if that helps.

Also, if you are interested, here are the settings I am using on the Chroma Key:
- ATEM Television Studio HD
- Upstream Key 1: Chroma
- Hue: 321 degrees
- Gain: 100%
- Y Surpress: 69%
- Lift: 25%
- Narrow Chroma Key Range: checked

**Comment by jvens** [comment] 2019-10-17 00:54
OK, I take back a little bit of what I just said.  I am not sure what happened the first time, but the chroma color was not showing through the background at all I think.  I refreshed the page and it turned much more magenta than before.  If I use the ideal settings for everything else it just doesn't key out the magenta at all.  When I get the settings such that it starts to key out the border everything else is looking very grainy and not very good.  Also, it doesn't partially key it out and make it darker, it is just an all or nothing.  I will likely plan to do the same as @Tomrish and edit the files directly for the events this weekend.

My opinion is to just make the border around the box some shade of grey and not try to chroma any of it out.  Personally I think that would work just fine, and save a lot of us a lot of headache trying to tune chroma keys.  Also, it will be easier to throw this screen up without needing to worry about camera feeds.

**Comment by maths22** [comment] 2021-09-21 00:03
This is resolved in v3 (for Freight Frenzy).  Note that the background is now just pure video background without any grey over it.

**Closed by maths22** 2021-09-21 00:03 UTC
Labels: In Development
