### ISSUE TITLE
Scoretracker can score end-game only points prior to end-game period.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#5] opened 2018-09-17 12:06 UTC
Score Tracker – Driver-Controlled screen: The scoretracker is able to score end-game only points prior to the end-game period.

**Comment by adwiii** [comment] 2018-10-18 22:30
Closing this as a duplicate of #49. Any follow-up discussion should occur under that issue.

**Closed by adwiii** 2018-10-18 22:30 UTC
