### ISSUE TITLE
Display config reset on disconnection

### ISSUE THREAD

**Issue by ShaharIlany** [FIRST-Tech-Challenge/scorekeeper#691] opened 2024-01-14 15:14 UTC
**Describe the bug**
When a network error occurs for any reason, and the display disconnects from the server, the config resets and an FTA should reconfigure all the reconnected displays again.

**To Reproduce**
1. Start the server
2. Open on the server the Match Control page
3. Enter test mode and show a preview of a test game
4. Go to the video switch and scroll down to see the connected displays (No displays are currently connected)
5. Go to another computer and open a new display
6. Set the display name and customize the config
7. Disconnect the display from the network
8. Wait for a few seconds
9. Connect the display back to the network
10. See some weird things on the Connected Displays section

**Expected behavior**
The config for a certain display should be persistant on the computer (local storage) or at least for the current session (session storage)

**Screenshots**

*At the end of the video, you can see that the display is in overlay mode but on the Connected Displays sections, the display is configured as Audience Display. On every edit of the Display from the Match Control page, all the settings reset.

![Sequence01_2-ezgif com-optimize (2)](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/e03b99b3-2642-4532-bb27-77fd67e15e90)

**Device (please complete the following information):**
 - OS: [e.g. iOS] Server on MacOS 14.1.1 (23B81). Display on Windows 11 Pro (Arm version)
 - Browser [e.g. chrome, safari] Match Control Page on Chrome
 for mac 120.0.6099.216 (arm64). Display on Chrome 118.0.5993.118 (32-bit emulated)
 - Version [e.g. 22] v5.2.6

Disclaimer:
I've tested it in a pre season event with another computer for the Display and the results were the same. The specs above are the sepcs for my home lab environment

**Comment by jvens** [comment] 2024-01-14 18:39
I believe this is a duplicate of #684

**Comment by ShaharIlany** [comment] 2024-01-18 06:45
Indeed.

Although the problem doesn't only happen when the server is restarted as mentioned in #684, but on any disconnection between the display and the server.

**Comment by maths22** [comment] 2024-01-22 20:02
This has been resolved in v5.2.8

**Closed by maths22** 2024-01-22 20:02 UTC
Labels: bug, Local
