### ISSUE TITLE
Mobile Friendly View of Match Control

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#314] opened 2019-01-22 02:51 UTC
I have tried on the Kindle Fire 7, 8, and 10, but the alignment of the tables is horribly misaligned resulting in significant complications when trying to edit a prior match from a mobile device. Thanks to this misalignment, to edit Qualification 15, the user must select the edit button on the same line as, and right next to, Qualification 16.

This is just one example of how the interface could be made more accessible for mobile devices, but would be very helpful.

**Comment by jvens** [comment] 2019-01-22 05:18
This is a duplicate of issue #210

**Comment by maths22** [comment] 2022-09-28 15:23
While we don't recommend using the control page on a mobile device and don't design it with that use case in mind, it should now be usable on a mobile device without confusion (it still looks pretty ugly and scrolls a bunch, but the layout is preserved)

**Closed by maths22** 2022-09-28 15:23 UTC
