### ISSUE TITLE
Suggestion, not an issue

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#44] opened 2018-10-03 22:19 UTC
Is it possible that if we are setting up an event with the actual event date, that when creating the schedule for matches that it automatically utilizes the actual event date entered at the start rather than having to modify if setting up the event schedule a day earlier.  Also will the time be military format or will it be standard when all said and done?

**Comment by adwiii** [comment] 2018-10-08 22:05
This is a duplicate of #46. As such, I am closing this issue since #46 has a more explanatory title.

As a note, for now the plan is to stay in military time since that is unambiguous.

**Closed by adwiii** 2018-10-08 22:05 UTC
