### ISSUE TITLE
Manual Entry of Scores Issues

### ISSUE THREAD

**Issue by FTCCoachLinda** [FIRST-Tech-Challenge/scorekeeper#83] opened 2018-10-16 21:07 UTC
The end game parking defaults to out being checked. It is possible to have Out/Partial/In and Latched all be checked, but really only one of these should be possible.

![image](https://user-images.githubusercontent.com/31944476/47047575-f0673d80-d165-11e8-9c6f-bc9ba8f09dad.png)

Also after I created a test match and tried to enter the scores, It would not allow me to commit or post the scores from the manual entry window. When I went out of it, the entered scores were lost.

**Comment by cmacfarl** [comment] 2018-10-16 21:49
Why would we want all of them to be checked?  That forces a ref to do more work to uncheck them, and could possibly lead to errors if this extra step is not performed?

**Comment by FTCCoachLinda** [comment] 2018-10-16 21:55
My point is that the software allows both a parking and a latching which are not allowed in the game rules. We don't want them to all be checked. We want the automatically checked "out" to become unchecked when any of the other conditions IS checked.

**Comment by cmacfarl** [comment] 2018-10-16 21:59
Ah, thank you for the clarification.  That makes sense.

Duplicate of #71

**Comment by adwiii** [comment] 2018-10-17 00:00
Unable to reproduce this error. Reopening until we can verify the issues.

**Comment by adwiii** [comment] 2018-10-18 04:11
We believe this has been fixed in v0.4.1. There are some other similar issues with test matches that we have logged and will resolve soon. @FTCCoachLinda if you get a chance, can you try to verify that the specific errors mentioned here do not occur in v0.4.1. If they do occur, you can reopen this issue.

**Closed by adwiii** 2018-10-18 04:11 UTC

**Comment by FTCCoachLinda** [comment] 2018-10-18 20:39
I tried to recreate the issues and they are fixed in 4.1

Are test match results, if manually entered stored anywhere within the software (viewable after the fact)? And are they shown on the audience display (sorry, don't have the auxiliary display to check)?

Reason for above two questions: My league is having a practice meet next weekend, and I am not going to create a match schedule since only a few teams will have robots ready to participate. I was thinking of using the test matches to make it flexible, since this meet doesn't count.
