### ISSUE TITLE
How is high score calculated for league rankings

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#447] opened 2019-11-10 03:18 UTC
We had a question come up after one of our league meets today about why the ranking reports says that a teams highest score is 45 when the scored 52 in one of their matches.  I looked at the team history and because they have won more than 10 matches and the match that they scored 52 in they didn't win, but instead tied that match is not counted in their ranking.  Is this the correct way to calculate highest match score?  I know highest score is only used as a third tiebreaker and is unlikely to actually matter, but that team was very confused and a little frustrated.

[RoboMinions.pdf](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3828023/RoboMinions.pdf)

**Comment by adwiii** [comment] 2019-11-10 03:36
Yes, this is correct.

In League rankings, a team is ranked based on their 10 best matches from pre-League Tournament play. Here, "best" is determined by taking all matches and sorting them based on the standard 3 criteria that teams are sorted on (RP, TBP, High score), in order because these matches will maximize their ranking compared to other teams. 

Because high score is the third order tiebreaker, it is always advantageous to select a match with a higher RP/TBP, but lower high score because later on when the rankings are performed you would rather have those RP/TBP instead of the high score so that you do not resort to the lower order tiebreakers.

I know it can seem frustrating to a team that the high score shown is not the highest score they received, but you can assure them that the system chooses the 10 best matches to maximize their ranking.

I am closing this issue as this is intended behavior, but I am happy to continue discussing it in this thread if you have additional questions.

**Closed by adwiii** 2019-11-10 03:36 UTC
