### ISSUE TITLE
inspection scheduling error - fails to create

### ISSUE THREAD

**Issue by FTCCoachLinda** [FIRST-Tech-Challenge/scorekeeper#305] opened 2019-01-18 17:47 UTC
When creating an inspection schedule in 7.3 (and actually previously in 5.4), I get an error that says, "It appears that a Server error occurred. Please contact your FTA." and then in smaller font below Error 500.  I adjusted the number of stations and deleted judging. 

Any ideas? This is a fresh install and I was just running a test event.

**Comment by adwiii** [comment] 2019-01-18 17:53
Can you post exactly what numbers you were using and I will look into it. Thanks.

**Comment by FTCCoachLinda** [comment] 2019-01-18 18:03
I was using 15 minutes for robot and field inspectons and 2 stations for each. I did change the other setting on the dashboard to have field inspection split between phone and field. Does that help?

**Comment by adwiii** [comment] 2019-01-18 18:05
Also how many teams at the event?

**Comment by FTCCoachLinda** [comment] 2019-01-18 18:08
10

**Comment by adwiii** [comment] 2019-01-18 18:20
Thanks. I have identified the error - it will be fixed in the next release. The problem is that the system is expecting a two digit month on the time, but is autopopulating it with 1 digit month (1 for January instead of 01). After next release it will accept both, but for now you can get around this by changing the month to 01.

![image](https://user-images.githubusercontent.com/9453262/51405013-1f090180-1b23-11e9-97e3-e7f778725213.png)
(Above image is what is happening now - replace with 01 and it will work)

**Comment by FTCCoachLinda** [comment] 2019-01-18 18:58
Thank you!

**Comment by adwiii** [comment] 2019-02-06 07:18
This has been fixed in a previous release - it will now accept both 2 digit and 1 digit months.

**Closed by adwiii** 2019-02-06 07:18 UTC
