### ISSUE TITLE
early match scores don't save/post or count into rankings

### ISSUE THREAD

**Issue by jlaipunahou** [FIRST-Tech-Challenge/scorekeeper#160] opened 2018-11-04 07:36 UTC
Today, at the end of our second League Event, the first three matches did not contribute to the rankings even though the results it was shown in match control. When we were all finished with the event, we wanted to practice passing on data to our third League Event for next week. After successfully importing the .db file, the first three matches were missing so we re-entered it in based on paper scoresheets.

After that, we were ok and we hope the latest version posted this week will be better for our next event on Nov 10.

h2-1.db is the file that when you import it, you should see the missing Q1-3
h2-FINAL.db is the file that when you import it, you should see a complete Q1-14

On a related note, h1-FINAL.db shows Q1-7 missing from last week (0.4.3) so I am requesting the paper scoresheets from last week to re-enter the values so we can get the official results for the two events.

***I can't seem to upload DB files so let me know how you want me to pass it on to you, if you want.

Thank you!

**Comment by tvbarnette999** [comment] 2018-11-04 07:42
Does it let you upload them to issues if you zip it first? On Windows, select it, then right click and select "Send to..." then "Compressed folder".

**Comment by jlaipunahou** [comment] 2018-11-04 07:44
Thanks @tvbarnette999 

It's been a long day and I can't think straight :)

[Hawaii bugs.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2545651/Hawaii.bugs.zip)

**Comment by tvbarnette999** [comment] 2018-11-04 09:40
Thanks for the db! I see exactly what you described. All of the affected matches are committed in the database as 0-0, with all fields saved as 0. The interesting thing is it has the matches marked as played, and I can see randomization values for them (h2: 1,2,5), (h1:1,3,1,1,6,6,1), which indicates somehow the match was saved, but when it was saved all the scores were 0. Is there any chance you still have the original server instance running from the event? I would be very curious to know if the match state listed on the match control page shows "COMMITTED" for all of them, since you mentioned the control page showing the correct scores. Although if it has since been shutdown, then those pages should match what we are seeing now.

Did you notice this on import, or was the match results page showing this as well on the original server during the event?

Also, I am seeing that match 1 was committed 39 times, all 0s except for when you did it at 6:58PM (my machine may or may not be converting that to EST). Some of these are multiple commits per second. Do you know if the commit button was seeming to not work or take a long time, which might lead a user to repeatedly press it?

I am very sorry you have run into this, and we will can dig into this and figure out what went wrong as quickly as we can.

**Comment by vwestin** [comment] 2018-11-05 13:53
We had a couple of matches on Saturday that were showing up in the pit display as 'unplayed.' We believe we had done the 'commit & post' on each, since we have been treating the matches the same. We went back to the match list and saw the option to post the scores, which updated the records and all was fine. I am just wondering if these matches may not have been committed/posted (process completed) at the end of those matches. We also had to do the manual refresh on the pit display to refresh new match results (as reported in issue 162).

**Comment by adwiii** [comment] 2018-11-05 13:59
@vwestin If you were using the "This Event Only" pit display, then it is the same issue as #162 - that pit display has an internal issue that prevents it from refreshing itself and will be fixed next release.

As for the other portion, if the "Commit & Post" button is green and clickable then everything should be good to go - I do not think there would be any other issue there. When you say the post updated the records, to which records are you referring?

Is there a way other than the Pit display that you say the matches listed as unplayed?

To clarify, we have examined the db that @jlaipunahou provided, and the issue is not that the match is unplayed, but instead that the match has a saved score of 0-0. We will continue investigating what could have caused this.

**Comment by jlaipunahou** [comment] 2018-11-05 17:43
> Thanks for the db! I see exactly what you described. All of the affected matches are committed in the database as 0-0, with all fields saved as 0. The interesting thing is it has the matches marked as played, and I can see randomization values for them (h2: 1,2,5), (h1:1,3,1,1,6,6,1), which indicates somehow the match was saved, but when it was saved all the scores were 0. Is there any chance you still have the original server instance running from the event? I would be very curious to know if the match state listed on the match control page shows "COMMITTED" for all of them, since you mentioned the control page showing the correct scores. Although if it has since been shutdown, then those pages should match what we are seeing now.
> 
No, we do not have that. I should've taken screenshots. Too much during chaos during the event :)

> Did you notice this on import, or was the match results page showing this as well on the original server during the event?
> 

Thank you for your quick work on this. Unfortunately, I do not have the .log files and I have learned my lesson for future debugging :)

While it was running, the problem matches' scores did save, but it showed up as 0-0 in the HTML summary and did not factor into rankings. When we exported, shutdown (to simulate our next Event) and re-import, then the scores were lost

> Also, I am seeing that match 1 was committed 39 times, all 0s except for when you did it at 6:58PM (my machine may or may not be converting that to EST). Some of these are multiple commits per second. Do you know if the commit button was seeming to not work or take a long time, which might lead a user to repeatedly press it?
> 
That's good you can see my multiple clicks! I kept clicking commit, but it would not turn grey to blue. I'm pretty sure the matches that did show did not have this problem.

> I am very sorry you have run into this, and we will can dig into this and figure out what went wrong as quickly as we can.

Thank you again.

**Comment by jlaipunahou** [comment] 2018-11-05 17:44
> Could you also upload any log files from the h2 system? Also, to help us narrow this down - was this only using paper scoring entry?

As mentioned in other notes, I did not save the .log files (wasn't aware of them) since I was trying to start from scratch and remove the old server/instance. I have learned my lesson :)

This was only paper scoring entry.

**Comment by jlaipunahou** [comment] 2018-11-06 22:18
@tvbarnette999 how do I view a .db file? The first event (h1) shows full rankings (all teams played 5 matches), but Q1-7 shows blank. I suspect the data is actually in the file but just not showing in the HTML output. What's the best way to view the .db file? I don't want to have to re-enter the matches in order to force it to properly show.

As mentioned in other threads, h2 (second event) had the same problem of Q1-3 missing even though it showed all teams played 5 matches, but we discovered this at the event and quickly re-entered them in. 

Thank you!

**Comment by tvbarnette999** [comment] 2018-11-06 22:46
Your issue is actually different than those. Most similar issues are just display issues, which we are fairly confident we have fixed for this week's release. In those situations, restarting the server should fix the problem. Unfortunately, your situation is worse in that the data is not in the database file (hence the High Priority tag). So far, yours is the only scenario that we know of where that has occurred, and have spent the last 3 days trying to figure out how it could have happened and adding checks to reduce the likelihood it happens, notify the user when it might be happening, and saving snapshots of match data at different points in time in the match flow to make it easier to recover if it does happen.

The easiest way to check the contents of the database is to restart the server, and navigate to the URLs described in the [3rd Party API](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation) to view the data. This obviously does not show all the data in the database, but enough to know the data is there. If you take this route during an event to check, be sure to save screenshots or write down any data you can see that you believe is wrong if you are doing live scoring and don't have the paper scoresheets. You will also need to relogin to any displays or other pages. Alternatively, you can open the db folder, copy the file that contains your event code, move it to another instance of the server on another computer, use the Server Management page on that instance to import that file, and view it there, leaving the original server untouched and still running.

**Comment by jlaipunahou** [comment] 2018-11-07 02:50
Thanks for the clarifications.

I was able to view via the 3rd Party API.

I see that indeed Q1-7 is blank. I also see that the rankings convey all 14 teams have competed in 5 (just as we saw in the HTML output).

Is it safe to assume that somehow it has calculated the proper final rankings even though we can't find the Q1-7 data? I know this is the very problem you all are working hard to figure out. I just want to confirm that this is also how limited you are able to see.

**Comment by adwiii** [comment] 2018-11-07 03:16
The rankings data are being calculated using the blank values for Q1-7, and are thus incorrect. It is showing that all teams have completed 5 matches because the system thinks that Q1-7 have a final score of 0-0.

At this stage, retrieving the paper scoresheets is the only solution I have for rectifying the situation.

**Comment by jlaipunahou** [comment] 2018-11-07 22:02
Thanks. We've re-entered the matches according to the score sheets and I think we are ready to go for the third event this weekend. Looking forward to the next release.

**Comment by tvbarnette999** [comment] 2018-11-08 00:17
Could you upload a copy of the databases with the back-filled information? It might help our testing to see the correct values and walk through the entire process.

And we'll have the next release ready soon, which should reduce the chances of this happening again, hopefully detect it, and make recovering easier. If you see anything similar at or after your next event, please let us know.

**Comment by jlaipunahou** [comment] 2018-11-08 00:31
Here you go.
[h1-FINAL-2.db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2559835/h1-FINAL-2.db.zip)

**Comment by tvbarnette999** [comment] 2018-11-10 01:12
Thanks @jlaipunahou! Looks like all the matches have data now! I noticed in that db file the league history data still reflects the old data, due to that data being created separately on initial archive (details in #181). Here's the updated db file that includes the corrected league history data. Use this when doing the league import at the next event. I'm sorry I didn't check this earlier. If you've already imported to the next event, that's OK, we can resolve it afterwards, the league rankings will just be wrong until we do.
[h1.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2567954/h1.zip)

(Note, the db was updated in v0.5.2. League importing this file should work fine into any version, but don't do a server-level data import of this file into a version before 5.2).

**Comment by jvens** [comment] 2018-11-12 21:34
I believe that we may have had an event in Iowa with this same issue this weekend.  I have attached the database that was copied half way through the event.  I was not at the event, but my understanding is after completely closing out of the server and reopening it they were then able to save the scores for that match into the database.  I don't currently have the log files, but I am reaching out to see if I can get them as well.

[glenn_2018-11-10_meet1.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2573676/glenn_2018-11-10_meet1.zip)

**Comment by jlaipunahou** [comment] 2018-11-14 02:02
> Thanks @jlaipunahou! Looks like all the matches have data now! I noticed in that db file the league history data still reflects the old data, due to that data being created separately on initial archive (details in #181). Here's the updated db file that includes the corrected league history data. Use this when doing the league import at the next event. I'm sorry I didn't check this earlier. If you've already imported to the next event, that's OK, we can resolve it afterwards, the league rankings will just be wrong until we do.
> [h1.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2567954/h1.zip)
> 
> (Note, the db was updated in v0.5.2. League importing this file should work fine into any version, but don't do a server-level data import of this file into a version before 5.2).

@tvbarnette999 thanks for catching that. Actually, this is the same issue that I just realized we needed to account for. I didn't have a chance to digest your note till now when I had the same realization. I also just read [https://github.com/FIRST-Tech-Challenge/scorekeeper/issues/181](url)

To recap what you already know:
h1 happened on 10/27, with the the first 7 matches missing
h2 happened on 11/3 (with the wrong h1 data)
h3 happened on 11/11 (importing h2 that had the wrong h1 data; even though I had just corrected h1 to rescore the 7 missing matches, but I didn't think at the time that I had to "replay" the subsequent League Events so that the one .db file would have everything correct)

In short, would you all be able to help us fix this? I am attaching the h2-FINAL.db (with the wrong h1 info, but all h2 matches are scored properly) and the most recent h3.db (called "kauai3.db") that has the wrong h2.db

You already have the correct h1-FINAL-2

Thank you! Our next event is this Saturday :)

[fixingH league.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2578891/fixingH.league.zip)

**Comment by tvbarnette999** [comment] 2018-11-14 03:45
@jlaipunahou 
Here you go:
[kauai3-final.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2579088/kauai3-final.zip)

This can be used as the league import file into your next event, and it should be good to go with the correct data for all three meets.

As discussed in #181, you can also do a server import of this database to see the current rankings & verify it if you'd like. If you do this, make sure it's into v0.5.2 or higher.

We have adjusted the archive process in the release coming later this week such that if a match is edited after the event had already been archived, re-downloading the event archive will have the updated league data in it. However, if the old/wrong archive is imported into a future meet before the corrected one then the data will reflect the old one and it is currently not possible for general users to fix that, but we can do it for you.

@jvens Thanks for the db and logs! Everything helps us track this down. I'm glad you noticed and were able to recover.

**Comment by maths22** [comment] 2022-11-03 22:50
It seems this has not been an issue for a few seasons

**Closed by maths22** 2022-11-03 22:50 UTC
Labels: High Priority
