### ISSUE TITLE
Regenerate match list after adding/removing team from event

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#75] opened 2018-10-13 20:38 UTC
After the match list is generated if a team is added or removed from the event it is impossible to rerun the match list generator.  You can click the button and it will appear to run, but the actual match list does not change from when it was first run.  This is important if a team was inadvertently added to the event when they were not actually present and this was not detected until after match maker is run.

**Comment by adwiii** [comment] 2018-10-13 21:03
Duplicate of #45. I am closing #45 since this has a more descriptive title.

**Comment by adwiii** [comment] 2018-10-18 04:07
Re-running MatchMaker is supported in v0.4.1. There are still a few display bugs regarding running MatchMaker, but the functionality is there and the bugs have been logged. If MatchMaker appears to hang, simply refresh the page.

**Closed by adwiii** 2018-10-18 04:07 UTC
