### ISSUE TITLE
Counting time is not logical

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#333] opened 2019-02-01 11:36 UTC
We started 2 match(one per division) at exactly the same time, initially it showed that the clocks were compatible but slowly one clock showed less time until one end ended 10 seconds before the other

**Comment by adwiii** [comment] 2019-02-01 17:03
Can you describe the setup? Both divisions running on one computer? How were the display computers connected to the main computer? We will look into it.

**Comment by ofekashery** [comment] 2019-02-01 17:07
One computer for the server
One computer for the audience display.
And 2 computers - one for each division for match control

I'll try to send you video for this

**Comment by adwiii** [comment] 2019-02-01 17:08
Is this a duplicate of #332?

**Comment by ofekashery** [comment] 2019-02-01 17:09
I think that no

**Comment by maths22** [comment] 2021-09-21 00:00
This should be resolved in in v3 (for Freight Frenzy), please reopen if you see this happening this season.

**Closed by maths22** 2021-09-21 00:00 UTC
