### ISSUE TITLE
Attempting to create display "It appears that a Server error occurred. Please contact your FTA. Error 500"

### ISSUE THREAD

**Issue by tcflanag** [FIRST-Tech-Challenge/scorekeeper#142] opened 2018-11-01 05:23 UTC
I first saw this on 0.4.3,  but it is just repeated on 0.5.0.  I think it's related to closing out a display then trying to re-open it, but I've been unable to consistently repeat it. Restarting the server seems to clean it up.

Is there a debug switch I can turn on to produce detailed logs to help with this the next time it appears

I'm running on Win7, and running in Chrome.

![image](https://user-images.githubusercontent.com/24835710/47834556-2e1ab780-dd5d-11e8-99d2-559403a5967d.png)

[2018_10_31_09_54_18_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2537311/2018_10_31_09_54_18_PM_err.log)

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2537306/db.zip)

**Comment by adwiii** [comment] 2018-11-01 05:32
Can you post a screenshot with the URL, a list of steps to reproduce, the database file, and what version you were running?

**Comment by adwiii** [comment] 2018-11-01 05:40
What is the URL of the page you are accessing?

**Comment by tcflanag** [comment] 2018-11-01 05:42
I've definitely seen it when initially happen when starting a display on localhost, but after that it affects all displays.

http://localhost/event/or_sf_00/display/ 

The simply click "Start" with the default settings.

**Comment by adwiii** [comment] 2018-11-01 06:03
Hm. Okay. I cannot reproduce the bug locally, and if you are unable to reliably reproduce the bug then this will take some working on. 

Is it when you hit "Save" at the bottom of the settings panel it then immediately presents you with an error page? Is it while something is happening on the control page? Is the URL of the error page also http://localhost/event/or_sf_00/display/?

I will keep looking into this, and if you can isolate any steps that cause this to happen, please reply to this issue with the steps.

**Comment by adwiii** [comment] 2018-11-01 16:07
I have been able to duplicate this issue this morning. Is it possible that you had already loaded a match for play and then committed that match before trying to open a new display?

**Comment by tcflanag** [comment] 2018-11-01 16:33
That sounds likely. I know I was bouncing around testing work scorekeeper
event work flows, so I was mid "event". I then decided to add a second
display.  I hadn't fully connected the two events in my head.

**Comment by pmichaud** [comment] 2018-11-01 18:35
We've had this problem happen to us repeatedly in 0.4.3, across multiple scrimmage/testing events.   The problem reliably occurs for us after connecting two audience displays to the scoring system, or after disconnecting/reconnecting an audience display  (e.g., to switch from Live Scoring to Match Timer display or vice-versa).

The only reliable solution we've found is to restart the host scoring system and then re-connect all of the displays (and referee tablets and anything else that happens to be logged into the scoring system).

Pm

**Comment by pmichaud** [comment] 2018-11-01 18:37
P.S.:  Our scoring system is also running Windows 7, in case that makes a difference.

**Comment by adwiii** [comment] 2018-11-01 18:46
We have isolated the bug. It was introduced in 0.4.3 and will be corrected in a patch later today. Thank you for bringing this to our attention.

**Comment by adwiii** [comment] 2018-11-01 21:02
This has been fixed in v0.5.1 which we just posted. Please let us know if you have any other issues.

**Closed by adwiii** 2018-11-01 21:02 UTC
