### ISSUE TITLE
Show Video Only (Overlay) Renders Incorrectly with Scoring Bar at Top

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#402] opened 2019-10-02 09:21 UTC
When a display has the scoring bar location set to top, the chroma key fails to cover up the top portion of the display when the "Show Video Only (Overlay)" is selected.
See attached pictures for clarification.
![image](https://user-images.githubusercontent.com/28027434/66032692-002d8c80-e545-11e9-8c97-a9e7f73bac74.png)
![image](https://user-images.githubusercontent.com/28027434/66032723-0e7ba880-e545-11e9-9cc5-1b064883d206.png)

**Comment by GamingWithaAlexYouTube** [comment] 2019-10-02 13:04
Don’t know what problem you are having it workable fine for me you did not do it right in obs

**Comment by jvens** [comment] 2019-10-02 13:15
@bsimmons99, I was able to replicate the issue.

If it helps the dev team, the problem is `#chroma.vflip {top: 252px;}` on line `display.css:231` which is needed during a match, but should not be set in the full video overlay mode.

**Comment by adwiii** [comment] 2019-10-10 19:31
This was fixed in v1.1.0

**Closed by adwiii** 2019-10-10 19:31 UTC
Labels: In Development
